### ISSUE TITLE
Configure fails with libmcfp-1.3.2: 

### ISSUE THREAD

**Issue by yurivict** [mhekkel/mrc#15]
```
CMake Error at CMakeLists.txt:89 (target_link_libraries):
  Target "mrc" links to:

    libmcfp::libmcfp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at CMakeLists.txt:90 (target_link_libraries):
  Target "mrc-bootstrap" links to:

    libmcfp::libmcfp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

**Comment by mhekkel** [comment]
That fix in libmcfp was not good enough... I'm sorry. Should be fixed now.

**Comment by yurivict** [comment]
Sorry, but mrc still fails to configure on systems with no internet access.

**Comment by yurivict** [comment]
Please remove FetchContent* instructions: they shouldn't be needed on well maintained systems.

**Comment by mhekkel** [comment]
You're right, sorry about that. Will fix

**Comment by mhekkel** [comment]
Fixed, and tested on FreeBSD 14
